# Create a sample GitHub Actions workflow file for a JavaScript (Node.js) project
workflow_content = """name: Node.js SBOM and Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sbom-and-security:
    runs-on: ubuntu-latest
    name: Generate SBOM and Scan for Vulnerabilities

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM from source
        run: |
          syft dir:. -o cyclonedx-json > sbom-source.json

      - name: Install Trivy
        run: |
          sudo apt-get install wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Run Trivy scan
        run: |
          trivy fs . --severity HIGH,CRITICAL --format json --output trivy-results.json

      - name: Upload SBOM and Trivy results
        uses: actions/upload-artifact@v3
        with:
          name: security-artifacts
          path: |
            sbom-source.json
            trivy-results.json
"""

# Save the workflow file
with open(".github/workflows/nodejs-sbom.yml", "w") as f:
    f.write(workflow_content)

# Confirm creation
print("GitHub Actions workflow file 'nodejs-sbom.yml' has been created in .github/workflows/")

