name: Generate SBOM

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sbom:
    name: SBOM Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM from Dockerfile
        run: |
          syft packages dockerfile:. -o cyclonedx-json > sbom-dockerfile.json

      - name: Generate SBOM from source code
        run: |
          syft dir:. -o cyclonedx-json > sbom-source.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sbom-files
          path: |
            sbom-dockerfile.json
            sbom-source.json
      - name: Install Trivy
        run: |
          sudo apt-get install wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Scan Dockerfile for vulnerabilities
        run: |
          trivy fs . --severity HIGH,CRITICAL --format json --output trivy-results.json
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.json

